### ISSUE TITLE
"_asm{}" doesn't work

### ISSUE THREAD

**Issue by zhcong** [miracl/MIRACL#32]
This is error:
`error C4235: nonstandard extension used : '_asm' keyword not supported on this architecture`
I want to make the lib file with vs2005, It seem that AMV4I does't support the "_asm{}". Use .asm file may deal this problem. But I have no idea with the assembly language.

**Comment by mcarrickscott** [comment]
Hello,

What file were you compiling when you got this error, and please send us
the mirdef.h file you were using

Thanks...

Mike

**Comment by zhcong** [comment]
The error occurred in the file `mrarth1.c` `mrarth2.c` `mrfast.c` `mrmonty.c` `mrmuldv.c` `mrscrt.c`, they are all the same error type like this
 `..\..\..\..\out\mrarth1.c(251) : error C4235: nonstandard extension used : '_asm' keyword not supported on this architecture`,
And the mirdef.h file I use belong to this master branch without any change.
Thanks for your reply.

**Comment by mcarrickscott** [comment]
OK, thanks for that. The problem arises because at some stage Microsoft
dropped support for in-line assembly. Thing is we are not sure when exactly.

I am assuming that MIRACL is defined as 32 in mirdef,h

We don't have VS2005 here (in fact that compiler is no longer supported by
Microsoft).

At the bottom of the file miracl.h you will find the lines

/* Microsoft C */

    #ifdef _MSC_VER
    #ifndef M_I86HM
.....
        #if _MSC_VER>=1000
            #if MIRACL==32
                #define INLINE_ASM 3        /* --> problem is here (we
think). This should NOT be defined */
            #endif
        #endif
    #endif
    #endif


To definitely identify the problem and to fix it we need to know the value
of _MSC_VER

You can simply print it out, using printf

We *suspect* that the fix is to change the above to

/* Microsoft C */

    #ifdef _MSC_VER
    #ifndef M_I86HM
.....
        #if _MSC_VER>=1000
            #if _MSC_VER<1300      /* new line to exclude later versions of
VS */
              #if MIRACL==32
                  #define INLINE_ASM 3        /* --> problem is here (I
think). This should NOT be defined */
              #endif
           #endif
        #endif
    #endif
    #endif


but we cannot test it here.


Mike

**Comment by zhcong** [comment]
Thinks for your reply. `_MSC_VER` is`1500` in vs2005, and I change the file miracl.h, it work now.
But there still one file don't work `mrmuldv.c`, it don't have any sign just like "#if _MSC_VER>=1000", it use "_asm{}" in any case. How to deal it?

**Comment by zhcong** [comment]
now I add this code
`#define MR_NOASM 1` in the file mirdef.h, and delete all the code of mrmuldv.c. Then it work with any error. Will it be error when I use it?
Thinks.

**Comment by mcarrickscott** [comment]
That's fine. Alternatively copy mrmuldv.ccc to mrmuldv.c and use that
instead with the original mirdef.h

But you should really get a more modern 64-bit compiler!

Mike

**Comment by zhcong** [comment]
Thank for your help!
