### ISSUE TITLE
Question about line function in ake12bnx.cpp

### ISSUE THREAD

**Issue by SysFlat** [miracl/MIRACL#37]
hello,

Recently we are implementing R-ate pairing on BN curve: **y^2= x^3+5**.Our tower extension fileld is **1-2-4-12**.But now we get problem about the line function in miller loop--the difference between our results is only a negative indication.I don`t konw why and  I wonder if you can give me some advice .
### Line function formula in affine coordinate that we get is as below:
     
![default](https://cloud.githubusercontent.com/assets/19515782/20590118/1f00e824-b25c-11e6-8cd7-f90c1f2c731a.png)

### The code in ake12bnx.cpp looks like below:
    ZZn12 w;
    ZZn4 nn,dd,cc;
    ZZn2 X,Y;
	if (get_mip()->TWIST==MR_SEXTIC_D)
	{
		nn.set((ZZn2)-Qy,Y-slope*X);
		dd.set(slope*Qx);
	}
    w.set(nn,dd,cc);
Then the formula that I conclude from your code is as follows:
![default](https://cloud.githubusercontent.com/assets/19515782/20590165/7d4cac9c-b25c-11e6-95a1-fe9fad128c22.png)

You can easily find the difference between our results is only a negative indication. I'm confused about this for a long time, and I hope you can give me some advice. 

Thank you for your answer.

**Comment by mcarrickscott** [comment]
Hello,

The answer is that - it does not matter. Both forms are correct, and both
will cause the pairing to evaluate to the same result.

In fact you can multiply the line function by any constant, and still you
will get the same overall result. You can go further and multiply each line
function by a different random number and still get the same result.(Indeed
this may be useful to deflect side-channel attacks)

The reason is because of the final exponentiation. The final exponent has a
component that is (p-1). So a constant component x of the Miller function
will become x^(p-1), which is equal to 1 (Fermat's theorem).

So use whatever constant you want, ideally one that minimizes the cost of
calculating the line function.

Mike

**Comment by SysFlat** [comment]
Thank you very much for your prompt reply and it is very useful to me .
